name: Tests

on: push

# Action docs:
# https://github.com/actions/checkout#readme
# https://github.com/actions-rs/toolchain#readme
# https://github.com/Swatinem/rust-cache#readme
# https://github.com/actions-rs/cargo#readme

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.54.0 # MSRV
          - stable
          - nightly
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          default: true
      -
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: tests
          key: ${{ github.ref }}
      -
        name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      -
        name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
